### ISSUE TITLE
Yang kurang

### ISSUE THREAD

**Issue by kresnasatya** [wdharmana/CinemaTix#4]
1. Button share harus diimplementasikan
2. Buat kelas util untuk konversi angka ke currency
3. Buat semacam form validation agar user tidak meninggalkan inputan kosong khususnya di EditText
4. Optional: me-refactor koding
5. Buat TODO

**Comment by wdharmana** [comment]
Update :
1. Buat TO-DO
2. Optional: refactor code

**Comment by dekzitfz** [comment]
ntaps

**Comment by kresnasatya** [comment]
Suba liwat oi. Wkwkwk

**Comment by wdharmana** [comment]
wah segar sekali

**Comment by dekzitfz** [comment]
kesegaran yg hqq

**Comment by kresnasatya** [comment]
makin segarrrrrr

Salam,
Satya Kresna

https://github.com/satyakresna
www.linkedin.com/in/satyakresna

**Comment by awidiyadew** [comment]
```m e n g g o e n c a n g```
